# Generated by .github/workflows/release.yml on each v* tag — do not hand-edit.
class Lore < Formula
  desc "Memory knowledge-graph for AI coding-agent sessions + repos (single binary)"
  homepage "https://github.com/lucheeseng827/loregraph"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/lucheeseng827/loregraph/releases/download/v#{version}/lore-aarch64-apple-darwin.tar.gz"
      sha256 "5841c79575356bad1dbdfcc99799aae74221a262aa9bada41ebaa66e32b7aff5"
    end
    on_intel do
      url "https://github.com/lucheeseng827/loregraph/releases/download/v#{version}/lore-x86_64-apple-darwin.tar.gz"
      sha256 "e52cbf308b2795829f9fec46ebfcfe93baf40b63e8a448e6d169de36d15a0c95"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lucheeseng827/loregraph/releases/download/v#{version}/lore-aarch64-unknown-linux-musl.tar.gz"
      sha256 "2c0b16c79f49840cab995561f2ae7da8ce14ff42a0e5510fe9064fb4e428041a"
    end
    on_intel do
      url "https://github.com/lucheeseng827/loregraph/releases/download/v#{version}/lore-x86_64-unknown-linux-musl.tar.gz"
      sha256 "cc249b056c1ea5ac59ec3c38f98f9adbb3b5d997fbb800cfc5911b685a985335"
    end
  end

  def install
    bin.install "lore"
  end

  test do
    assert_match "lore", shell_output("#{bin}/lore version")
  end
end
