# Generated by .github/workflows/release.yml on each v* tag — do not hand-edit.
class Lore < Formula
  desc "Memory knowledge-graph for AI coding-agent sessions + repos (single binary)"
  homepage "https://github.com/lucheeseng827/loregraph"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/lucheeseng827/loregraph/releases/download/v#{version}/lore-aarch64-apple-darwin.tar.gz"
      sha256 "78b2fbca932599fd09d8a324eb26863feb9b75cf80e6f513602ef7f6fb5472d7"
    end
    on_intel do
      url "https://github.com/lucheeseng827/loregraph/releases/download/v#{version}/lore-x86_64-apple-darwin.tar.gz"
      sha256 "fe57cb6e1fb10716aa8f5e6e6315ecd5eb380a2592590e85ab6e4797f606650c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lucheeseng827/loregraph/releases/download/v#{version}/lore-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4065f1d59560bf8f460a624b586a4636a8d9b57ed5d6a64c63b8c38f89bc6c55"
    end
    on_intel do
      url "https://github.com/lucheeseng827/loregraph/releases/download/v#{version}/lore-x86_64-unknown-linux-musl.tar.gz"
      sha256 "d1df1cb43cb761ca8fb680dc0c2daf421ab1e4d7a25293ef9a1e1ca4910cdf19"
    end
  end

  def install
    bin.install "lore"
  end

  test do
    assert_match "lore", shell_output("#{bin}/lore version")
  end
end
