# Generated by .github/workflows/release.yml on each v* tag — do not hand-edit.
class Lore < Formula
  desc "Memory knowledge-graph for AI coding-agent sessions + repos (single binary)"
  homepage "https://github.com/lucheeseng827/loregraph"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/lucheeseng827/loregraph/releases/download/v#{version}/lore-aarch64-apple-darwin.tar.gz"
      sha256 "0b9671c4be9fdfe1a222ce007ad6ed1606e824c3ff851421e22b0d9df1970c28"
    end
    on_intel do
      url "https://github.com/lucheeseng827/loregraph/releases/download/v#{version}/lore-x86_64-apple-darwin.tar.gz"
      sha256 "81d9a6121ea3d7cb0953c7312eb411e65efb22c8ab03bc2763d9d8f40b041115"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lucheeseng827/loregraph/releases/download/v#{version}/lore-aarch64-unknown-linux-musl.tar.gz"
      sha256 "e0af7591c4530b1f87e3dcac6402bc59e9ee4c93da1fa4a173878e18c9849672"
    end
    on_intel do
      url "https://github.com/lucheeseng827/loregraph/releases/download/v#{version}/lore-x86_64-unknown-linux-musl.tar.gz"
      sha256 "3c2f6cb7d1317a2e67c52f6be7f79387649d19fef3caafa59caf8f4be5496904"
    end
  end

  def install
    bin.install "lore"
  end

  test do
    assert_match "lore", shell_output("#{bin}/lore version")
  end
end
